### ISSUE TITLE
This program just run on OSX?

### ISSUE THREAD

**Issue by momentwdj** [ba01ei/imessager#2]
How about find iMessage's protocol and use it on all device

**Comment by ba01ei** [comment]
Apple takes security very seriously, so that's going to be a little hard.

**Comment by momentwdj** [comment]
Yep, I tried it,but can't find the protocol of iMessage.If it can run on PC server,can help developer to save SMS fee.Poor man do not have MAC.^_^

**Comment by ba01ei** [comment]
The new plan is to support sending google talk messages. In that way it will be able to run on PC/linux servers, and also be able to push to Android phones.
